# Week 6 - Data Wrangling Practice 2

In this notebook we will apply the **same data cleaning and preprocessing techniques** used in the student performance exercise, but now with a different dataset.

The goal is to reinforce the workflow while being agnostic of a specific dataset.

In [2]:
# uncomment if you need any of those
# !pip install pandas numpy

**Import necessary libraries**

In [10]:
import pandas as pd
import numpy as np
from pathlib import Path

## Dataset

In this section, we will work with a **dirty** version of a breast cancer dataset.

Workflow steps we will cover:
- loading a CSV with the correct separator
- removing accidental index columns
- cleaning column names
- standardizing categorical values
- fixing numeric columns polluted with text
- handling missing values, duplicates, and outliers

## 1. Inspecting the dataset

### Q1.1 Define the path to the dirty file

In [16]:
# your code here
raw_path = Path("../raw/breast-cancer-wisconsin/dirty/breast-cancer-dirty.csv")

### Q1.2 Load the dataset

Before anything, we must load the dataset correctly.

Try loading it once without specifying the separator. What happens?

In [19]:
# your code here
df = pd.read_csv(raw_path)
df.head()

  ; Index ;Radius 1 ; Texture 1;Perimeter-1;Area 1; Smoothness 1 ;Compactness 1;Concavity 1;Concave Points 1;Symmetry 1;Fractal Dimension 1;Radius 2;Texture 2;Perimeter 2;Area 2;Smoothness 2;Compactness 2;Concavity 2;Concave Points 2;Symmetry 2;Fractal Dimension 2;Radius 3;Texture 3;Perimeter 3;Area 3;Smoothness 3;Compactness 3;Concavity 3;Concave Points 3;Symmetry 3;Fractal Dimension 3;Diagnosis ;Tumor Side;Referral Type ;Hospital Region
0  0;0;17.99;10.38 units;122.8;1001.0;0.1184;0.27...
1  1;1;20.57;17.77;132.9;1326.0;0.08474;0.07864;0...
2  2;2;19.69; 21.25 ;130.0;1203.0;0.1096;0.1599;0...
3  3;3;11.42;20.38;77.58;386.1;0.1425;0.2839;0.24...
4  4;4;20.29;14.34;135.1;1297.0;0.1003;0.1328;0.1...

Now try again using `sep`

In [21]:
# your code here
df = pd.read_csv(raw_path, sep=";")
df.head()

,Unnamed: 0,Index,Radius 1,Texture 1,Perimeter-1,Area 1,Smoothness 1,Compactness 1,Concavity 1,Concave Points 1,...,Smoothness 3,Compactness 3,Concavity 3,Concave Points 3,Symmetry 3,Fractal Dimension 3,Diagnosis,Tumor Side,Referral Type,Hospital Region
0,0,0,17.99,10.38 units,122.80,1001.0,0.11840,0.27760,0.3001,0.14710,...,0.1622,0.6656,0.7119,0.2654,0.4601,0.1189 level,malignant,left,urgent,north
1,1,1,20.57,17.77,132.90,1326.0,0.08474,0.07864,0.0869,0.07017,...,0.1238,0.1866,0.2416,0.1860,0.2750,0.08902,benign,RIGHT,Routine,SOUTH
2,2,2,19.69,21.25,130.00,1203.0,0.10960,0.15990,0.1974,0.12790,...,0.1444,0.4245,0.4504,0.2430,0.3613,0.08758,M,Lt,URG,E
3,3,3,11.42,20.38,77.58,386.1,0.14250,0.28390,0.2414,0.10520,...,0.2098,0.8663,0.6869,0.2575,0.6638,0.173,b,rt,routine-case,west-side
4,4,4,20.29,14.34,135.10,1297.0,0.10030,0.13280,0.1980,0.10430,...,0.1374,0.2050,0.4000,0.1625,0.2364,0.07678,M,unknown,?,NaN

In [29]:
df.columns

Index(['Unnamed: 0', ' Index ', 'Radius 1 ', ' Texture 1', 'Perimeter-1',
       'Area 1', ' Smoothness 1 ', 'Compactness 1', 'Concavity 1',
       'Concave Points 1', 'Symmetry 1', 'Fractal Dimension 1', 'Radius 2',
       'Texture 2', 'Perimeter 2', 'Area 2', 'Smoothness 2', 'Compactness 2',
       'Concavity 2', 'Concave Points 2', 'Symmetry 2', 'Fractal Dimension 2',
       'Radius 3', 'Texture 3', 'Perimeter 3', 'Area 3', 'Smoothness 3',
       'Compactness 3', 'Concavity 3', 'Concave Points 3', 'Symmetry 3',
       'Fractal Dimension 3', 'Diagnosis ', 'Tumor Side', 'Referral Type ',
       'Hospital Region'],
      dtype='object')

**It seems that someone saved the index by mistake... Lets get rid of it!**

### Q1.3 Drop the unnamed/index column if it exists.

In [31]:
# your code here
df.drop(columns=["Unnamed: 0"," Index "], inplace=True)

In [33]:
df.columns

Index(['Radius 1 ', ' Texture 1', 'Perimeter-1', 'Area 1', ' Smoothness 1 ',
       'Compactness 1', 'Concavity 1', 'Concave Points 1', 'Symmetry 1',
       'Fractal Dimension 1', 'Radius 2', 'Texture 2', 'Perimeter 2', 'Area 2',
       'Smoothness 2', 'Compactness 2', 'Concavity 2', 'Concave Points 2',
       'Symmetry 2', 'Fractal Dimension 2', 'Radius 3', 'Texture 3',
       'Perimeter 3', 'Area 3', 'Smoothness 3', 'Compactness 3', 'Concavity 3',
       'Concave Points 3', 'Symmetry 3', 'Fractal Dimension 3', 'Diagnosis ',
       'Tumor Side', 'Referral Type ', 'Hospital Region'],
      dtype='object')

### Q1.4 How many rows and columns are there in this dataset?

In [35]:
# your code here
df.shape

(572, 34)

### Q1.5 Check the data type of each column

In [37]:
# your code here
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 572 entries, 0 to 571
Data columns (total 34 columns):
 #   Column               Non-Null Count  Dtype
---  ------               --------------  -----
 0   Radius 1             572 non-null    float64
 1    Texture 1           552 non-null    object
 2   Perimeter-1          572 non-null    float64
 3   Area 1               572 non-null    float64
 4    Smoothness 1        540 non-null    float64
 5   Compactness 1        572 non-null    float64
 6   Concavity 1          572 non-null    float64
 7   Concave Points 1     572 non-null    float64
 8   Symmetry 1           572 non-null    float64
 9   Fractal Dimension 1  572 non-null    float64
 10  Radius 2             572 non-null    float64
 11  Texture 2            551 non-null    float64
 12  Perimeter 2          572 non-null    float64
 13  Area 2               572 non-null    float64
 14  Smoothness 2         545 non-null    object
 15  Compactness 2        572 non-null    float64
 16  Concavity 2          572 non-null    float64
 17  Concave Points 2     572 non-null    float64
 18  Symmetry 2           572 non-null    float64
 19  Fractal Dimension 2  572 non-null    float64
 20  Radius 3             572 non-null    float64
 21  Texture 3            543 non-null    float64
 22  Perimeter 3          572 non-null    float64
 23  Area 3               572 non-null    object
 24  Smoothness 3         572 non-null    float64
 25  Compactness 3        572 non-null    float64
 26  Concavity 3          572 non-null    float64
 27  Concave Points 3     572 non-null    float64
 28  Symmetry 3           572 non-null    float64
 29  Fractal Dimension 3  572 non-null    object
 30  Diagnosis            552 non-null    object
 31  Tumor Side           552 non-null    object
 32  Referral Type        552 non-null    object
 33  Hospital Region      535 non-null    object
dtypes: float64(26), object(8)
memory usage: 152.1+ KB

### Q1.6 Verify descriptive statistics

In [39]:
# your code here
df.describe()

,Radius 1,Perimeter-1,Area 1,Smoothness 1,Compactness 1,Concavity 1,Concave Points 1,Symmetry 1,Fractal Dimension 1,Radius 2,...,Symmetry 2,Fractal Dimension 2,Radius 3,Texture 3,Perimeter 3,Smoothness 3,Compactness 3,Concavity 3,Concave Points 3,Symmetry 3
count,572.000000,572.000000,572.000000,540.000000,572.000000,572.000000,572.000000,572.000000,572.000000,572.000000,...,572.000000,572.000000,572.000000,543.000000,572.000000,572.000000,572.000000,572.000000,572.000000,572.000000
mean,14.275802,99.867605,760.327098,0.095349,0.104755,0.089303,0.049110,0.181365,0.062862,0.406051,...,0.020611,0.003808,16.277708,25.764383,107.333042,0.132568,0.255966,0.273793,0.115015,0.290861
std,5.024773,64.656586,930.563274,0.029362,0.053256,0.079866,0.038804,0.027619,0.007201,0.277246,...,0.008406,0.002650,4.825727,6.159151,33.551138,0.023049,0.159894,0.209589,0.065889,0.063932
min,6.981000,43.790000,143.500000,-0.500000,0.019380,0.000000,0.000000,0.106000,0.049960,0.111500,...,0.007882,0.000895,7.930000,12.020000,50.410000,0.071170,0.027290,0.000000,0.000000,0.156500
25%,11.697500,75.247500,420.300000,0.086320,0.065175,0.029575,0.020348,0.161975,0.057697,0.233225,...,0.015175,0.002249,13.025000,21.185000,84.147500,0.116600,0.147575,0.115925,0.064967,0.250350
50%,13.375000,86.965000,556.950000,0.095785,0.094035,0.061680,0.033770,0.179250,0.061545,0.325000,...,0.018740,0.003207,14.970000,25.460000,97.745000,0.131400,0.213000,0.229000,0.100550,0.282250
75%,15.797500,106.375000,805.625000,0.105300,0.130500,0.132150,0.074067,0.195750,0.066165,0.482725,...,0.023482,0.004560,18.795000,29.905000,125.525000,0.146150,0.340325,0.385300,0.162500,0.318475
max,99.900000,736.000000,11856.000000,0.163400,0.345400,0.426800,0.201200,0.304000,0.097440,2.873000,...,0.078950,0.029840,36.040000,49.540000,251.200000,0.222600,1.058000,1.252000,0.291000,0.663800

## 2. Preprocessing

Now that we have some information about the dataset, it is clear that there are many problems.

Let's preprocess this dataset to make it cleaner and more reliable for future analysis and later database insertion.

### Q2.1 Define a function to clean the column names

In [51]:
# your code here
df.columns = [col.strip().lower() for col in df.columns]

### Q2.2 Verify the cleaned column names

In [54]:
# your code here
df.columns

Index(['radius 1', 'texture 1', 'perimeter-1', 'area 1', 'smoothness 1',
       'compactness 1', 'concavity 1', 'concave points 1', 'symmetry 1',
       'fractal dimension 1', 'radius 2', 'texture 2', 'perimeter 2', 'area 2',
       'smoothness 2', 'compactness 2', 'concavity 2', 'concave points 2',
       'symmetry 2', 'fractal dimension 2', 'radius 3', 'texture 3',
       'perimeter 3', 'area 3', 'smoothness 3', 'compactness 3', 'concavity 3',
       'concave points 3', 'symmetry 3', 'fractal dimension 3', 'diagnosis',
       'tumor side', 'referral type', 'hospital region'],
      dtype='object')

<details>
<summary style="background-color: #fff3cd; padding: 10px; border-radius: 5px; cursor: pointer;">
    <h2 style="display: inline;">
        Understanding Numerical vs. Categorical Data
        <span style="color: red; font-size: 0.8em;">(click to expand/collapse)</span>
    </h2>
</summary>

<div style="padding: 10px; background-color: #f8f9fa; border-radius: 5px;">

<p>
Numerical columns can be used for calculations such as averages, medians, or outlier detection. Categorical columns represent labels or classes and usually need standardization before analysis.
</p>

<p>
Even when a column should be numerical, dirty datasets may contain values such as <code>"15 mm2"</code> or <code>" ?"</code>. This forces us to clean and convert the data before continuing.
</p>

</div>
</details>

### Q2.3 Create a categorical list

In [56]:
# your code here
categorical_cols = ['diagnosis', 'tumor side', 'referral type', 'hospital region']

### Q2.4 Create a numerical list

In [58]:
# your code here
numerical_cols = ['radius 1', 'texture 1', 'perimeter-1', 'area 1', 'smoothness 1',
'compactness 1', 'concavity 1', 'concave points 1', 'symmetry 1',
'fractal dimension 1', 'radius 2', 'texture 2', 'perimeter 2', 'area 2',
'smoothness 2', 'compactness 2', 'concavity 2', 'concave points 2',
'symmetry 2', 'fractal dimension 2', 'radius 3', 'texture 3',
'perimeter 3', 'area 3', 'smoothness 3', 'compactness 3', 'concavity 3',
'concave points 3', 'symmetry 3', 'fractal dimension 3']

### Q2.5 Inspect unique values in selected categorical columns

In [60]:
# your code here
for col in categorical_cols:
    print(f"\nColumn: {col}")
    print(df[col].unique())

Column: diagnosis
['malignant' ' benign ' 'M ' 'b' 'M' '?' nan 'B' 'm' ' M ' ' B ' ' b ']

Column: tumor side
[' left ' 'RIGHT' 'Lt' 'rt' 'unknown' 'Right' 'Left' nan]

Column: referral type
['urgent' 'Routine ' 'URG' 'routine-case' ' ?' 'Urgent' nan 'Routine']

Column: hospital region
['north ' 'SOUTH' 'E' 'west-side' nan 'South' 'East' 'North' 'West']

### Q2.6 Replace inconsistent missing markers with `NaN`

Examples of markers that may appear:
- `?`
- ` ?`
- `unknown`
- `N/A`

In [64]:
# your code here
df.replace(["?", " ?", "unknown", "N/A", ""], np.nan, inplace=True)

### Q2.7 Check for missing values in every column

In [67]:
# your code here
df.isna().sum()

radius 1                0
texture 1              43
perimeter-1             0
area 1                  0
smoothness 1           32
compactness 1           0
concavity 1             0
concave points 1        0
symmetry 1              0
fractal dimension 1     0
radius 2                0
texture 2              21
perimeter 2             0
area 2                  0
smoothness 2           41
compactness 2           0
concavity 2             0
concave points 2        0
symmetry 2              0
fractal dimension 2     0
radius 3                0
texture 3              29
perimeter 3             0
area 3                 14
smoothness 3            0
compactness 3           0
concavity 3             0
concave points 3        0
symmetry 3              0
fractal dimension 3     6
diagnosis              32
tumor side             38
referral type          35
hospital region        37
dtype: int64

### Q2.8 Which columns are the most problematic in terms of missing values?

In [ ]:
# your code here
#As colunas mais problemáticas em termos de valores em falta são tumor side,
#hospital region, referral type, diagnosis, texture 1, smoothness 2 e texture 3.

### Q2.9 Define a function that checks the percentage of missing values for a given column

**Example:**

```python
def percentage_missing_values(df: pd.DataFrame, col: str) -> float:
    return (df[col].isna().sum() / len(df)) * 100
```

In [69]:
# your code here
def percentage_missing_values(df: pd.DataFrame, col: str) -> float:
    return (df[col].isna().sum() / len(df)) * 100

percentage_missing_values(df,"texture 1")

7.517482517482517

## 3. Standardizing categorical values

Now that missing markers are fixed, we must standardize inconsistent categories.

Examples of dirty values that may appear:
- `malignant`, `M`, `M `
- `left`, `Left`, `Lt`, ` left `
- `urgent`, `URG`, `Routine `

### Q3.1 Define helper functions to standardize selected categorical fields

In [71]:
# your code here
def clean_category(series: pd.Series) -> pd.Series:
    return (
        series.astype(str)
        .str.strip()
        .str.lower()
    )

### Q3.2 Apply the categorical standardization to the DataFrame

In [73]:
# your code here
for col in categorical_cols:
    df[col] = clean_category(df[col])

### Q3.3 Recheck the unique values after standardization

In [75]:
# your code here
for col in categorical_cols:
    print(f"\nColumn: {col}")
    print(df[col].unique())

Column: diagnosis
['malignant' 'benign' 'm' 'b' 'nan']

Column: tumor side
['left' 'right' 'lt' 'rt' 'nan']

Column: referral type
['urgent' 'routine' 'urg' 'routine-case' 'nan']

Column: hospital region
['north' 'south' 'e' 'west-side' 'nan' 'east' 'west']

## 4. Fixing column types

Some numerical columns seems to be polluted with strings.

Examples:
- `18.4 units`
- `99999 mm2`

### Q4.1 Define a function that coerces selected columns to numeric

In [79]:
# your code here
def to_numeric_clean(series: pd.Series) -> pd.Series:
    return pd.to_numeric(
        series.astype(str).str.replace(r"[^\d.]", "", regex=True))

for col in numerical_cols:
    df[col] = to_numeric_clean(df[col])

### Q4.2 Check `.info()` again after type conversion

In [81]:
# your code here
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 572 entries, 0 to 571
Data columns (total 34 columns):
 #   Column               Non-Null Count  Dtype
---  ------               --------------  -----
 0   radius 1             572 non-null    float64
 1   texture 1            521 non-null    float64
 2   perimeter-1          572 non-null    float64
 3   area 1               572 non-null    float64
 4   smoothness 1         540 non-null    float64
 5   compactness 1        572 non-null    float64
 6   concavity 1          572 non-null    float64
 7   concave points 1     572 non-null    float64
 8   symmetry 1           572 non-null    float64
 9   fractal dimension 1  572 non-null    float64
 10  radius 2             572 non-null    float64
 11  texture 2            551 non-null    float64
 12  perimeter 2          572 non-null    float64
 13  area 2               572 non-null    float64
 14  smoothness 2         528 non-null    float64
 15  compactness 2        572 non-null    float64
 16  concavity 2          572 non-null    float64
 17  concave points 2     572 non-null    float64
 18  symmetry 2           572 non-null    float64
 19  fractal dimension 2  572 non-null    float64
 20  radius 3             572 non-null    float64
 21  texture 3            543 non-null    float64
 22  perimeter 3          572 non-null    float64
 23  area 3               558 non-null    float64
 24  smoothness 3         572 non-null    float64
 25  compactness 3        572 non-null    float64
 26  concavity 3          572 non-null    float64
 27  concave points 3     572 non-null    float64
 28  symmetry 3           572 non-null    float64
 29  fractal dimension 3  566 non-null    float64
 30  diagnosis            572 non-null    object
 31  tumor side           572 non-null    object
 32  referral type        572 non-null    object
 33  hospital region      572 non-null    object
dtypes: float64(30), object(4)
memory usage: 152.1+ KB

## 5. Missing value imputation

Now that types are cleaner, we can impute missing values more safely.

### Q5.1 Impute missing values for numerical columns
- A reasonable first option is the median

In [83]:
# your code here
for col in numerical_cols:
    df[col].fillna(df[col].median(), inplace=True)

C:\Users\ineko\AppData\Local\Temp\ipykernel_16664\2581620845.py:3: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  df[col].fillna(df[col].median(), inplace=True)

### Q5.2 Impute missing values for categorical columns
- A reasonable first option is the mode
- If no mode is available, use a fixed value such as `unknown`

In [85]:
# your code here

for col in categorical_cols:
    if df[col].mode().shape[0] > 0:
        df[col].fillna(df[col].mode()[0], inplace=True)
    else:
        df[col].fillna("unknown", inplace=True)

C:\Users\ineko\AppData\Local\Temp\ipykernel_16664\1631412622.py:5: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  df[col].fillna(df[col].mode()[0], inplace=True)

### Q5.3 Verify whether missing values still exist

In [89]:
# your code here
df.isna().sum().sum()

0

## 6. Duplicates and outliers

### Q6.1 Check duplicated rows

In [91]:
# your code here
df.duplicated().sum()

3

### Q6.2 Remove duplicated rows if necessary

In [93]:
# your code here
df.drop_duplicates(inplace=True)

### Q6.3 Verify if there are **outliers** in numerical columns using the `IQR method`

To detect outliers in a numerical column, we can use the **Interquartile Range (IQR) method**.

The formula works as follows:

- Compute the 1st quartile (Q1)
- Compute the 3rd quartile (Q3)
- Compute the IQR = Q3 - Q1
- Values below `Q1 - 1.5 * IQR` or above `Q3 + 1.5 * IQR` are treated as outliers

In [95]:
# your code here
def verify_outliers(df: pd.DataFrame, col: str) -> bool:
    q1 = df[col].quantile(0.25)
    q3 = df[col].quantile(0.75)
    iqr = q3 - q1

    lower = q1 - 1.5 * iqr
    upper = q3 + 1.5 * iqr

    return ((df[col] < lower) | (df[col] > upper)).any()

### Q6.4 Apply the outlier check to the numerical columns

In [97]:
# your code here
for col in numerical_cols:
    print(col, verify_outliers(df, col))

radius 1 True
texture 1 True
perimeter-1 True
area 1 True
smoothness 1 True
compactness 1 True
concavity 1 True
concave points 1 True
symmetry 1 True
fractal dimension 1 True
radius 2 True
texture 2 True
perimeter 2 True
area 2 True
smoothness 2 True
compactness 2 True
concavity 2 True
concave points 2 True
symmetry 2 True
fractal dimension 2 True
radius 3 True
texture 3 True
perimeter 3 True
area 3 True
smoothness 3 True
compactness 3 True
concavity 3 True
concave points 3 False
symmetry 3 True
fractal dimension 3 True

## 7. Preparing the dataset for later MongoDB insertion

At the end of this notebook, the data should be clean enough to be loaded later into MongoDB.

### Q7.1 Add metadata columns to the DataFrame

Expected values:
- `source_file`: `breast-cancer-dirty.csv`
- `source_dataset`: `Breast Cancer Wisconsin (dirty classroom version)`

In [99]:
# your code here
df["source_file"] = "breast-cancer-dirty.csv"
df["source_dataset"] = "Breast Cancer Wisconsin (dirty classroom version)"

### Q7.2 Inspect the final structure of the cleaned dataset

In [102]:
# your code here
df.info()

<class 'pandas.core.frame.DataFrame'>
Index: 569 entries, 0 to 568
Data columns (total 36 columns):
 #   Column               Non-Null Count  Dtype
---  ------               --------------  -----
 0   radius 1             569 non-null    float64
 1   texture 1            569 non-null    float64
 2   perimeter-1          569 non-null    float64
 3   area 1               569 non-null    float64
 4   smoothness 1         569 non-null    float64
 5   compactness 1        569 non-null    float64
 6   concavity 1          569 non-null    float64
 7   concave points 1     569 non-null    float64
 8   symmetry 1           569 non-null    float64
 9   fractal dimension 1  569 non-null    float64
 10  radius 2             569 non-null    float64
 11  texture 2            569 non-null    float64
 12  perimeter 2          569 non-null    float64
 13  area 2               569 non-null    float64
 14  smoothness 2         569 non-null    float64
 15  compactness 2        569 non-null    float64
 16  concavity 2          569 non-null    float64
 17  concave points 2     569 non-null    float64
 18  symmetry 2           569 non-null    float64
 19  fractal dimension 2  569 non-null    float64
 20  radius 3             569 non-null    float64
 21  texture 3            569 non-null    float64
 22  perimeter 3          569 non-null    float64
 23  area 3               569 non-null    float64
 24  smoothness 3         569 non-null    float64
 25  compactness 3        569 non-null    float64
 26  concavity 3          569 non-null    float64
 27  concave points 3     569 non-null    float64
 28  symmetry 3           569 non-null    float64
 29  fractal dimension 3  569 non-null    float64
 30  diagnosis            569 non-null    object
 31  tumor side           569 non-null    object
 32  referral type        569 non-null    object
 33  hospital region      569 non-null    object
 34  source_file          569 non-null    object
 35  source_dataset       569 non-null    object
dtypes: float64(30), object(6)
memory usage: 164.5+ KB

### Q7.3 Inspect a small sample of the final cleaned dataset

In [104]:
# your code here
df.sample(5)

,radius 1,texture 1,perimeter-1,area 1,smoothness 1,compactness 1,concavity 1,concave points 1,symmetry 1,fractal dimension 1,...,concavity 3,concave points 3,symmetry 3,fractal dimension 3,diagnosis,tumor side,referral type,hospital region,source_file,source_dataset
371,15.19,13.21,97.65,711.8,0.07963,0.06934,0.033930,0.02657,0.1721,0.05544,...,0.13620,0.08178,0.2487,0.06766,b,right,routine,north,breast-cancer-dirty.csv,Breast Cancer Wisconsin (dirty classroom version)
287,12.89,13.12,81.89,515.9,0.06955,0.03729,0.022600,0.01171,0.1337,0.05581,...,0.11860,0.05366,0.2309,0.06915,nan,lt,routine,north,breast-cancer-dirty.csv,Breast Cancer Wisconsin (dirty classroom version)
512,13.40,20.52,88.64,556.7,0.11060,0.14690,0.144500,0.08172,0.2116,0.07325,...,0.51060,0.20510,0.3585,0.11090,m,lt,urgent,north,breast-cancer-dirty.csv,Breast Cancer Wisconsin (dirty classroom version)
132,16.16,21.54,106.20,809.8,0.10080,0.12840,0.104300,0.05613,0.2160,0.05891,...,0.29920,0.13120,0.3480,0.07619,m,left,urgent,north,breast-cancer-dirty.csv,Breast Cancer Wisconsin (dirty classroom version)
419,11.16,21.41,70.95,380.3,0.10180,0.05978,0.008955,0.01076,0.1615,0.06144,...,0.03582,0.04306,0.2976,0.08005,b,right,routine,west,breast-cancer-dirty.csv,Breast Cancer Wisconsin (dirty classroom version)

### Q7.4 Export the cleaned dataset to CSV

Suggested file:
- `../../raw/breast-cancer-wisconsin/dirty/breast-cancer-cleaned.csv`

In [108]:
# your code here
df.to_csv("../raw/breast-cancer-wisconsin/dirty/breast-cancer-cleaned.csv",index=False)

## Final reflection

After finishing this notebook, you should be able to explain:
- what was dirty in the dataset
- which steps were needed to clean it
- why this preprocessing should happen **before** inserting the data into MongoDB
- how the cleaned dataset is now more suitable for later EDA and database loading